### ISSUE TITLE
Console [WARN] spam in 1.21

### ISSUE THREAD

**Issue by googleooer** [WizarTheGreat/MovableTileEntities#6]
I keep getting this warning message whenever someone powers a piston in my 1.21 server.

```[18:48:05 WARN]: [MovableTileEntities] Task #59812 for MovableTileEntities v1.2 generated an exception
java.lang.NumberFormatException: For input string: "21-R0"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
        at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
        at MovableTileEntities.jar/plugin.movabletileentities.MovableTileEntities.is20OrHigher(MovableTileEntities.java:25) ~[MovableTileEntities.jar:?]
        at MovableTileEntities.jar/plugin.movabletileentities.MovableTileEntities.lambda$move$0(MovableTileEntities.java:395) ~[MovableTileEntities.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1654) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by WizarTheGreat** [comment]
This is because it wasn't designed to check for snapshots.
Fixed and will be included the next update.
Thank you!
